version: "3.7"

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - MYSQL_USER=/run/secrets/mysql_user
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_net

  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=/run/secrets/mysql_user
      - MYSQL_PASSWORD=/run/secrets/mysql_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - nextcloud_net

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - nextcloud_net

volumes:
  nextcloud_data:
  db_data:

networks:
  nextcloud_net:
    driver: bridge
