version: "3.8"

services:
  # Pi-hole Service
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      - TZ=Europe/London # Change this to your time zone
      - WEBPASSWORD=your_admin_password # Set Pi-hole admin password
      - PIHOLE_DOCKER_TAG=latest
      - DNS1=8.8.8.8 # You can use Google DNS or another DNS server
      - DNS2=8.8.4.4 # You can use Google DNS or another DNS server
    ports:
      - "53:53/udp" # DNS port
      - "53:53/tcp" # DNS port (TCP)
      - "82:80" # Web interface
      - "444:443" # Web interface (if SSL enabled)
    volumes:
      - ./etc-pihole:/etc/pihole # Mount Pi-hole configuration directory
      - ./etc-dnsmasq.d:/etc/dnsmasq.d # Mount dnsmasq configuration directory
    networks:
      - app_network # Connect Pi-hole to your custom network
    restart: unless-stopped

  nginx_proxy_manager:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx_proxy_manager
    restart: always
    ports:
      - "80:80"
      - "81:81" # Admin interface
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  # MariaDB Service
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password # Change this to a strong password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: /run/secrets/mysql_password # Change this to a strong password
    volumes:
      - nextclouddb_data:/var/lib/mysql
    networks:
      - app_network

  # Nextcloud Service
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8080:80" # Exposes Nextcloud on port 8080
    environment:
      PHP_UPLOAD_MAX_SIZE: 2G
      PHP_MEMORY_LIMIT: 512M
      APC_SHM_SIZE: 128M
      OPCACHE_MEM_SIZE: 128M
      CRON_PERIOD: 15m
      MYSQL_PASSWORD: /run/secrets/mysql_password # Same as the DB password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: redispassword # You can change this password
      MEMCACHE_LOCAL: '\OC\Memcache\Redis' # Tells Nextcloud to use Redis for local caching
      REDIS_PORT: 6379
    volumes:
      - /srv/data/nextcloud/nextcloud_data:/var/www/html/data # Bind mount for user data
      - /srv/data/nextcloud/nextcloud_config:/var/www/html/config # Docker volume for config
      - /srv/data/nextcloud/nextcloud_themes:/var/www/html/themes # Custom the
    depends_on:
      - db
      - redis
    networks:
      - app_network

  # Redis Service for Nextcloud Caching
  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "redispassword"] # Set a password for Redis
    networks:
      - app_network

  # homarr:
  #   image: ghcr.io/ajnart/homarr:latest
  #   container_name: homarr
  #   restart: unless-stopped
  #   ports:
  #     - "7575:7575"
  #   volumes:
  #     - ${USERDIR}/homarr/config:/config
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - app_network

# Volumes for persistent data
volumes:
  nextclouddb_data:
    name: nextclouddb_data

# Network for both containers to communicate
networks:
  app_network:
    driver: bridge
