version: "3.8"

services:
  # MariaDB Service
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password # Change this to a strong password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: /run/secrets/mysql_password # Change this to a strong password
    volumes:
      - nextclouddb_data:/var/lib/mysql
    networks:
      - app_network

  # Nextcloud Service
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8080:80" # Exposes Nextcloud on port 8080
    environment:
      MYSQL_PASSWORD: /run/secrets/mysql_password # Same as the DB password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: redispassword # You can change this password
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - app_network

  # Redis Service for Nextcloud Caching
  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "redispassword"] # Set a password for Redis
    networks:
      - app_network

  # homarr:
  #   image: ghcr.io/ajnart/homarr:latest
  #   container_name: homarr
  #   restart: unless-stopped
  #   ports:
  #     - "7575:7575"
  #   volumes:
  #     - ${USERDIR}/homarr/config:/config
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - app_network

# Volumes for persistent data
volumes:
  nextclouddb_data:
  nextcloud_data:

# Network for both containers to communicate
networks:
  app_network:
    driver: bridge
