version: "3.7"

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - MYSQL_USER=/run/secrets/mysql_user
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    ports:
      - 8080:80
    volumes:
      - nextcloud_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_PASSWORD=/run/secrets/mysql_password
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - MYSQL_USER=/run/secrets/mysql_user
      - MYSQL_DATABASE=nextcloud
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - app_network

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - ${USERDIR}/homarr/config:/config
    environment:
      - NODE_ENV=production
    networks:
      - app_network

volumes:
  nextcloud_data:
  db_data:

networks:
  app_network:
    driver: bridge
