version: "3.8"

services:
  # Pi-hole Service
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard_home
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "83:80"
      - "442:443"
      - "3000:3000/tcp"
    volumes:
      - /srv/data/adguard.work:/opt/adguardhome/work
      - /srv/data/adguard.conf:/opt/adguardhome/conf
    environment:
      - TZ=Australia/Melbourne
    networks:
      - app_network # Connect Pi-hole to your custom network

  nginx_pm:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx_pm
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81" # Admin interface
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - /srv/data/nginxpm_data:/data
      - /srv/data/nginxpm_letsencrypt:/etc/letsencrypt
    networks:
      - app_network # Connect Pi-hole to your custom network

  # MariaDB Service
  nc_db:
    image: mariadb:latest
    container_name: nc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password # Change this to a strong password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: /run/secrets/mysql_password # Change this to a strong password
    volumes:
      - /srv/volume/nextclouddb_data:/var/lib/mysql
    networks:
      - app_network

  # Nextcloud Service
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8080:80" # Exposes Nextcloud on port 8080
    environment:
      MYSQL_PASSWORD: /run/secrets/mysql_password # Same as the DB password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: nc_db
      REDIS_HOST: nc_redis
      REDIS_HOST_PASSWORD: redispassword # You can change this password
      REDIS_PORT: 6379
    volumes:
      - /srv/data/nextcloud_data:/var/www/html/data # Bind mount for user data
      - /srv/data/nextcloud_config:/var/www/html/config # Docker volume for config
      - /srv/data/nextcloud_themes:/var/www/html/themes # Custom the
    depends_on:
      - nc_db
      - nc_redis
    networks:
      - app_network

  # Redis Service for Nextcloud Caching
  nc_redis:
    image: redis:alpine
    container_name: nc_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "redispassword"] # Set a password for Redis
    networks:
      - app_network

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - /srv/data/homarr_appdata:/appdata
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_ENCRYPTION_KEY=2bfd284f39d01c07913fd2b8a8fe43bbc9aaad3ae6c2983aa38c7ca49e2bd4c7
    networks:
      - app_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000" # Port for the Portainer web UI
    volumes:
      - /srv/data/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "89:80" # Adjust to your preferred port
    volumes:
      - /srv/volume/filebrowserdb_data:/database
      - /srv/data/filebrowser_files:/srv
    environment:
      - PUID=1000 # Adjust to your desired user ID
      - PGID=1000 # Adjust to your desired group ID
      - TZ=Australia/Melbourne
    networks:
      - app_network

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - app_network

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /srv/volume/im_model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - app_network

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - app_network

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - app_network

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:latest
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - /srv/data/homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - ha_mariadb
    environment:
      - TZ=Australia/Melbourne
    networks:
      - app_network

  ha_mariadb:
    container_name: ha_mariadb
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_DATABASE: homeassistant
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: /run/secrets/mysql_password
    volumes:
      - /srv/volume/homeassistantdb_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=ha_mariadb
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
    depends_on:
      - ha_mariadb
    networks:
      - app_network

  netdata:
    container_name: netdata
    image: titpetric/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    environment:
      - TZ=Australia/Melbourne
      #- PUID=1000
      #- PGID=1000
    ports:
      - 19999:19999
    volumes:
      - /srv/data/netdata_config:/etc/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock # To collect Docker metrics
    networks:
      - app_network

  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - /srv/data/speedtest_data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus UI
    volumes:
      - /srv/data/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml # Configuration file
      - /srv/data/prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3333:3000" # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Set Grafana admin password
    volumes:
      - /srv/data/grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8888:8080" # cAdvisor UI (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - app_network

# Volumes for persistent data
volumes:
  nextclouddb_data:
    name: nextclouddb_data
  immichdb_data:
    name: immichdb_data
  homeassistantdb_data:
    name: homeassistantdb_data
  filebrowserdb_data:
    name: filebrowserdb_data

# Network for both containers to communicate
networks:
  app_network:
    driver: bridge
